name: Codeception Tests

on:
  workflow_dispatch:
  pull_request:

jobs:

  ci:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '7.4', '8.0' ]
      fail-fast: false

    env:
      cache_version: 1 # increment to flush all caches
      php_extensions: memcached, mysql, bz2, gd, igbinary, imagick, imap, mbstring, bcmath, zip, intl
      COMPOSE_INTERACTIVE_NO_CLI: 1
      WP_ROOT_FOLDER: ${{ github.workspace }}/tests/wordpress
      WP_DOMAIN: "square1-acf-field-models.tribe"
      WP_ADMIN_PATH: "/wp-admin"
      WP_ADMIN_USERNAME: "admin"
      WP_ADMIN_PASSWORD: "password"
      WP_URL: "http://square1-acf-field-models.tribe"
      TEST_DB_HOST: 127.0.0.1
      TEST_DB_NAME: wordpress
      TEST_DB_USER: root
      TEST_DB_PASSWORD: password
      TABLE_PREFIX: "tribe_"
      TEST_CONFIG_FILE: "tests/wp-config-environment.php"

    services:

      mysql:
        image: mariadb:10
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: wordpress
        ports:
          - 3306:3306

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP extension cache
        id: cache-php-extensions
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.php_extensions }}
          key: ${{ matrix.operating-system }}-${{ env.cache_version }}-phpextensions-${{ matrix.php-versions }}-${{ matrix.wordpress-version }}

      - name: Cache PHP extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.cache-php-extensions.outputs.dir }}
          key: ${{ steps.cache-php-extensions.outputs.key }}
          restore-keys: ${{ steps.cache-php-extensions.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: ${{ env.php_extensions }}
          coverage: none
          tools: codeception, composer

      - name: Configure Tests
        run: | 
          composer test:setup
          rm -rf ./tests/.env
          touch ./tests/.env

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Check for Cached Composer Dependencies
        id: cache-composer-dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ env.cache_version }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-${{ env.cache_version }}-composer-

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader

      - name: Run integration tests
        run: composer test:integration
